# Use root/example as user/password credentials
# docker build -f dockermysql.yml
# COMMAND: docker-compose -f dockermysql.yml up -d
version: "3.7"
services:
  dbadminer:
    build:
      context: ./
      dockerfile: ./adminer.dockerfile
    image: adminer:1.0.0fd
    container_name: dbadminer
    restart: always
    ports:
      - 81:8080

  # postgres:
  #   image: postgres:9.6.17
  #   container_name: localpostgres
  #   restart: always
  #   user: postgres
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     # POSTGRES_DB: db
  #     # PGDATA: /data
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     # - C:\containers_data\postgres\data:/data
  #     - C:\containers_data\postgres\data:/var/lib/postgresql/data
  #     # - C:\containers_data\postgres:/var/lib/postgresql

  mysql:
    image: mysql:8.0.17
    container_name: localmysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      # - /home/buster/containers_data/mysql:/var/lib/mysql
      - C:\containers_data\mysql:/var/lib/mysql

  mssql:
    # image: microsoft/mssql-server-linux:2017-CU13
    # image: mcr.microsoft.com/mssql/server:2017-CU13
    # image: mcr.microsoft.com/mssql/server:2017-CU20-ubuntu-16.04
    image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
    # build:
    #   context: ./
    #   dockerfile: ./mssql.dockerfile
    # image: buster95/mssql:2019-CU2-ubuntu-16.04
    # user: root
    # ls -laR /var/opt/mssql
    # docker run -it --rm -v C:\containers_data\mssql:/var/opt/mssql --user root mcr.microsoft.com/mssql/server:2019-CU2-ubuntu-16.04 bash
    # command: >
    #   bash -c "chgrp -R 0 /var/opt/mssql
    #   && chmod -R g=u /var/opt/mssql
    #   && chown -R 10001:0 /var/opt/mssql
    #   && exit"
    container_name: localmssql
    restart: always
    user: root
    environment:
      TZ: America/Managua
      ACCEPT_EULA: "Y"
      SA_PASSWORD: StrongPassword@07
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: 1
    cap_add:
      - SYS_PTRACE
    ports:
      - 1433:1433
      # - 1434:1433
    volumes:
      - C:\containers_data\mssql:/var/opt/mssql/data
      # - data-mssql:/var/opt/mssql/data
      # - /home/buster/containers_data/mssql:/var/opt/mssql
      # - C:\containers_data\mssql:/var/opt/mssql

  mongodb:
    image: mongo:4.2.6
    container_name: localmongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - C:\containers_data\mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:5.0.8-buster
    container_name: localredis
    restart: always
    environment:
      REDIS_PASSWORD: 123456
    ports:
      - 6379:6379
    volumes:
      - data-redis:/data

volumes:
  data-mssql:
  data-mysql:
  data-redis:
