# Use root/example as user/password credentials
# docker build -f dockermysql.yml
# COMMAND: docker-compose -f dockermysql.yml up -d
version: '3.3'
services:

  dbadminer:
    build:
      context: ./
      dockerfile: ./adminer.dockerfile
    image: adminer:1.0.0fd
    container_name: dbadminer
    restart: always
    ports:
      - 81:8080

  mysql:
    image: mysql:8.0.17
    container_name: localmysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      # - /home/buster/containers_data/mysql:/var/lib/mysql
      - C:\containers_data\mysql:/var/lib/mysql

  mssql:
    # image: mcr.microsoft.com/mssql/server:latest
    image: microsoft/mssql-server-linux:2017-CU13
    # build:
      # context: ./
      # dockerfile: ./mssql.dockerfile
    # image: mssql:1.0.0fd
    container_name: localmssql
    restart: always
    environment:
      TZ: America/Managua 
      ACCEPT_EULA: Y
      SA_PASSWORD: StrongPassword@07
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: 1
    cap_add:
      - SYS_PTRACE
    ports:
      - 1433:1433
      - 1434:1433
    volumes:
      # - /home/buster/containers_data/mssql:/var/opt/mssql
      - C:\containers_data\mssql:/var/opt/mssql