version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer_service
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - data-portainer:/data portainer/portainer

volumes:
  data-portainer:
