apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitlab-service-account-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitlab-service-account
    namespace: uni
--- 
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRole
# metadata:
#   name: prom-admin
#   namespace: uni
# rules:
# - apiGroups: [""]
#   resources: ["*"] # ["pods", "nodes"]
#   verbs: ["get", "watch", "list"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#   name: prom-rbac
#   namespace: uni
# subjects:
# - kind: ServiceAccount
#   name: default
#   namespace: uni
# roleRef:
#   kind: ClusterRole
#   name: prom-admin
#   apiGroup: rbac.authorization.k8s.io
# ---
apiVersion: v1
kind: Service
metadata:
  name: gitlabuni
  namespace: uni
  labels:
    app: gitlabuni
  annotations:
    metallb.universe.tf/allow-shared-ip: gitlabuni
spec:
  selector:
    app: gitlabuni
  ports:
  - name: httpweb
    port: 80
    targetPort: 80
    protocol: TCP
  - name: httpsweb
    port: 443
    targetPort: 443
    protocol: TCP
  - name: sshport
    port: 22
    targetPort: 22
    protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 10.245.11.168
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlabuni
  namespace: uni
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlabuni
    spec:
      containers:
      - name: gitlabuni
        image: gitlab/gitlab-ee:12.5.1-ee.0
        imagePullPolicy: IfNotPresent
        env:
            # Add any other gitlab.rb configuration here, each on its own line          
          - name: GITLAB_OMNIBUS_CONFIG
            value: external_url \'http://git.uni.edu.ni\';
            # nginx['redirect_http_to_https'] = true; 
            # nginx['redirect_http_to_https_port'] = 80;
            # nginx['ssl_certificate'] = "/etc/gitlab/ssl/git.uni.edu.ni.crt";
            # nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/git.uni.edu.ni.key"
            # letsencrypt['enable'] = true;
            # letsencrypt['auto_renew_hour'] = "12";
            # letsencrypt['auto_renew_minute'] = "30";
            # letsencrypt['auto_renew_day_of_month'] = "*/7";
        ports:
          - name: httpweb
            containerPort: 80
            protocol: TCP
          - name: httpsweb
            containerPort: 443
            protocol: TCP
          - name: sshport
            containerPort: 22
            protocol: TCP
        volumeMounts:
          - name: data
            mountPath: /var/opt/gitlab
          - name: logs
            mountPath: /var/log/gitlab
          - name: config
            mountPath: /etc/gitlab
      volumes:
        - name: data
          hostPath:
            path: /storage/gitlab/data
        - name: logs
          hostPath:
            path: /storage/gitlab/logs
        - name: config
          hostPath:
            path: /storage/gitlab/config
---